// SPDX-License-Identifier: GPL-3.0

// Terminal options in the vendored VeloKit Config.zig. Keep names in engine spelling.
// Unsupported options are explicit errors, never silently accepted no-ops.
public enum TerminalSettings {
  public static let otherPlatformKeys: Set<String> = Set(unavailable.keys.filter {
    $0.hasPrefix("gtk-") || $0.hasPrefix("linux-cgroup") || ["class", "x11-instance-name", "freetype-load-flags"].contains($0)
  })
  public static let supported: Set<String> = [
    "focus-follows-mouse",
    "split-divider-color",
    "split-inherit-working-directory",
    "split-preserve-zoom",
    "unfocused-split-fill",
    "unfocused-split-opacity",
    "window-inherit-font-size",
    "window-inherit-working-directory",
    "window-show-tab-bar",

    "abnormal-command-exit-runtime",
    "adjust-box-thickness",
    "adjust-cell-height",
    "adjust-cell-width",
    "adjust-cursor-height",
    "adjust-cursor-thickness",
    "adjust-font-baseline",
    "adjust-icon-height",
    "adjust-overline-position",
    "adjust-overline-thickness",
    "adjust-strikethrough-position",
    "adjust-strikethrough-thickness",
    "adjust-underline-position",
    "adjust-underline-thickness",
    "alpha-blending",
    "background",
    "background-blur",
    "background-image",
    "background-image-fit",
    "background-image-opacity",
    "background-image-position",
    "background-image-repeat",
    "background-opacity",
    "background-opacity-cells",
    "bell-audio-path",
    "bell-audio-volume",
    "bell-features",
    "bold-color",
    "click-repeat-interval",
    "clipboard-codepoint-map",
    "clipboard-paste-bracketed-safe",
    "clipboard-paste-protection",
    "clipboard-read",
    "clipboard-trim-trailing-spaces",
    "clipboard-write",
    "clipboard-write-limit-bytes",
    "command",
    "command-palette-entry",
    "config-file",
    "confirm-close-surface",
    "copy-on-select",
    "cursor-click-to-move",
    "cursor-color",
    "cursor-opacity",
    "cursor-style",
    "cursor-style-blink",
    "cursor-text",
    "custom-shader",
    "custom-shader-animation",
    "desktop-notifications",
    "drag-handle",
    "enquiry-response",
    "env",
    "faint-opacity",
    "font-codepoint-map",
    "font-family",
    "font-family-bold",
    "font-family-bold-italic",
    "font-family-italic",
    "font-feature",
    "font-shaping-break",
    "font-size",
    "font-style",
    "font-style-bold",
    "font-style-bold-italic",
    "font-style-italic",
    "font-synthetic-style",
    "font-thicken",
    "font-thicken-strength",
    "font-variation",
    "font-variation-bold",
    "font-variation-bold-italic",
    "font-variation-italic",
    "foreground",
    "fullscreen",
    "grapheme-width-method",
    "image-storage-limit",
    "initial-command",
    "initial-window",
    "input",
    "key-remap",
    "keybind",
    "link-osc8",
    "link-previews",
    "link-url",
    "macos-auto-secure-input",
    "macos-hidden",
    "macos-non-native-fullscreen",
    "macos-option-as-alt",
    "macos-secure-input-indication",
    "macos-titlebar-proxy-icon",
    "macos-titlebar-style",
    "macos-window-buttons",
    "macos-window-shadow",
    "maximize",
    "middle-click-action",
    "minimum-contrast",
    "mouse-hide-while-typing",
    "mouse-reporting",
    "mouse-scroll-multiplier",
    "mouse-shift-capture",
    "notify-on-command-finish",
    "notify-on-command-finish-action",
    "notify-on-command-finish-after",
    "osc-color-report-format",
    "palette",
    "palette-generate",
    "palette-harmonious",
    "progress-style",
    "quit-after-last-window-closed",
    "quit-after-last-window-closed-delay",
    "resize-overlay",
    "resize-overlay-duration",
    "resize-overlay-position",
    "right-click-action",
    "scroll-to-bottom",
    "scrollback-compression",
    "scrollback-limit-bytes",
    "scrollback-limit-lines",
    "scrollbar",
    "search-background",
    "search-foreground",
    "search-selected-background",
    "search-selected-foreground",
    "selection-background",
    "selection-clear-on-copy",
    "selection-clear-on-typing",
    "selection-foreground",
    "selection-word-chars",
    "shell-integration",
    "shell-integration-features",
    "term",
    "theme",
    "title",
    "title-report",
    "vt-kam-allowed",
    "wait-after-command",
    "window-colorspace",
    "window-decoration",
    "window-height",
    "window-padding-balance",
    "window-padding-color",
    "window-padding-x",
    "window-padding-y",
    "window-position-x",
    "window-position-y",
    "window-save-state",
    "window-step-resize",
    "window-subtitle",
    "window-theme",
    "window-title-font-family",
    "window-titlebar-background",
    "window-titlebar-foreground",
    "window-vsync",
    "window-width",
    "working-directory",
    "tab-inherit-working-directory",
    "window-new-tab-position",
  ]

  public static let repeatable: Set<String> = [
    "clipboard-codepoint-map",
    "command-palette-entry",
    "config-file",
    "custom-shader",
    "env",
    "font-codepoint-map",
    "font-family",
    "font-family-bold",
    "font-family-bold-italic",
    "font-family-italic",
    "font-feature",
    "font-variation",
    "font-variation-bold",
    "font-variation-bold-italic",
    "font-variation-italic",
    "input",
    "key-remap",
    "keybind",
    "palette",
  ]

  public static let unavailable: [String: String] = [
    "link":
      "Custom link patterns are not implemented by the vendored engine; URL and OSC 8 links are supported.",
    "app-notifications": "This engine option applies only to GTK.",
    "async-backend": "Excluded; the app uses its built-in I/O backend.",
    "auto-update": "Deferred until application distribution is implemented.",
    "auto-update-channel": "Deferred until application distribution is implemented.",
    "class":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "config-default-files":
      "Uses the upstream configuration-file format and search policy; Velocitty loads its own TOML file.",
    "freetype-load-flags":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-custom-css":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-horizontal-tab-scroll":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-opengl-debug":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-quick-terminal-layer":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-quick-terminal-namespace":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-single-instance":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-tabs-location":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-titlebar":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-titlebar-hide-when-maximized":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-titlebar-style":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-toolbar-style":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "gtk-wide-tabs":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "language":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "linux-cgroup":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "linux-cgroup-hard-fail":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "linux-cgroup-memory-limit":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "linux-cgroup-processes-limit":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    "macos-applescript": "Excluded from the application.",
    "macos-custom-icon": "Excluded; the app uses fixed artwork.",
    "macos-dock-drop-behavior":
      "Velocitty inserts dropped paths into the selected terminal; configurable drop destinations are not implemented.",
    "macos-icon": "Excluded; the app uses fixed artwork.",
    "macos-icon-frame": "Excluded; the app uses fixed artwork.",
    "macos-icon-ghost-color": "Excluded; the app uses fixed artwork.",
    "macos-icon-screen-color": "Excluded; the app uses fixed artwork.",
    "macos-shortcuts": "Excluded from the application.",
    "quick-terminal-animation-duration": "Excluded; there is no quick-terminal window.",
    "quick-terminal-autohide": "Excluded; there is no quick-terminal window.",
    "quick-terminal-keyboard-interactivity": "Excluded; there is no quick-terminal window.",
    "quick-terminal-position": "Excluded; there is no quick-terminal window.",
    "quick-terminal-screen": "Excluded; there is no quick-terminal window.",
    "quick-terminal-size": "Excluded; there is no quick-terminal window.",
    "quick-terminal-space-behavior": "Excluded; there is no quick-terminal window.",
    "undo-timeout": "Deferred until terminal session restoration is implemented.",
    "x11-instance-name":
      "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
  ]
}
