// SPDX-License-Identifier: GPL-3.0

// Terminal options in the vendored VeloKit Config.zig. Keep names in engine spelling.
// Unsupported options are explicit errors, never silently accepted no-ops.
public enum TerminalSettings {
    public static let supported: Set<String> = [
        "command-palette-entry",
        "macos-secure-input-indication",
        "macos-auto-secure-input",
        "bell-audio-path",
        "bell-audio-volume",
        "bell-features",
        "desktop-notifications",
        "notify-on-command-finish",
        "notify-on-command-finish-action",
        "notify-on-command-finish-after",
        "progress-style",

        "scrollbar",
        "search-background",
        "search-foreground",
        "search-selected-background",
        "search-selected-foreground",

        "initial-window",
        "quit-after-last-window-closed",
        "quit-after-last-window-closed-delay",
        "confirm-close-surface",
        "window-save-state",
        "window-width",
        "window-height",
        "window-position-x",
        "window-position-y",
        "window-step-resize",
        "window-decoration",
        "window-colorspace",
        "window-theme",
        "macos-titlebar-style",
        "macos-window-buttons",
        "macos-window-shadow",
        "macos-hidden",
        "maximize",
        "fullscreen",
        "background-opacity",
        "background-opacity-cells",
        "background-blur",

        "shell-integration-features",
        "shell-integration",
        "clipboard-read",
        "clipboard-paste-protection",
        "clipboard-paste-bracketed-safe",

        "macos-option-as-alt",
        "cursor-click-to-move",
        "mouse-hide-while-typing",
        "mouse-shift-capture",
        "mouse-reporting",
        "mouse-scroll-multiplier",
        "selection-word-chars",
        "copy-on-select",
        "click-repeat-interval",
        "right-click-action",
        "link-url",
        "link-osc8",
        "link-previews",

        "theme",
        "config-file",
        "abnormal-command-exit-runtime",
        "adjust-box-thickness",
        "adjust-cell-height",
        "adjust-cell-width",
        "adjust-cursor-height",
        "adjust-cursor-thickness",
        "adjust-font-baseline",
        "adjust-icon-height",
        "adjust-overline-position",
        "adjust-overline-thickness",
        "adjust-strikethrough-position",
        "adjust-strikethrough-thickness",
        "adjust-underline-position",
        "adjust-underline-thickness",
        "alpha-blending",
        "background",
        "background-image",
        "background-image-fit",
        "background-image-opacity",
        "background-image-position",
        "background-image-repeat",
        "bold-color",
        "clipboard-codepoint-map",
        "clipboard-trim-trailing-spaces",
        "clipboard-write",
        "clipboard-write-limit-bytes",
        "command",
        "cursor-color",
        "cursor-opacity",
        "cursor-style",
        "cursor-style-blink",
        "cursor-text",
        "custom-shader",
        "custom-shader-animation",
        "enquiry-response",
        "env",
        "faint-opacity",
        "font-codepoint-map",
        "font-family",
        "font-family-bold",
        "font-family-bold-italic",
        "font-family-italic",
        "font-feature",
        "font-shaping-break",
        "font-size",
        "font-style",
        "font-style-bold",
        "font-style-bold-italic",
        "font-style-italic",
        "font-synthetic-style",
        "font-thicken",
        "font-thicken-strength",
        "font-variation",
        "font-variation-bold",
        "font-variation-bold-italic",
        "font-variation-italic",
        "foreground",
        "grapheme-width-method",
        "image-storage-limit",
        "initial-command",
        "input",
        "key-remap",
        "keybind",
        "minimum-contrast",
        "osc-color-report-format",
        "palette",
        "palette-generate",
        "palette-harmonious",
        "scroll-to-bottom",
        "scrollback-compression",
        "scrollback-limit-bytes",
        "scrollback-limit-lines",
        "selection-background",
        "selection-clear-on-copy",
        "selection-clear-on-typing",
        "selection-foreground",
        "term",
        "title",
        "title-report",
        "vt-kam-allowed",
        "wait-after-command",
        "window-padding-balance",
        "window-padding-color",
        "window-padding-x",
        "window-padding-y",
        "window-vsync",
        "working-directory",
    ]

    public static let repeatable: Set<String> = [
        "command-palette-entry",
        "config-file",
        "clipboard-codepoint-map",
        "custom-shader",
        "env",
        "font-codepoint-map",
        "font-family",
        "font-family-bold",
        "font-family-bold-italic",
        "font-family-italic",
        "font-feature",
        "font-variation",
        "font-variation-bold",
        "font-variation-bold-italic",
        "font-variation-italic",
        "input",
        "key-remap",
        "keybind",
        "palette",
    ]

    public static let unavailable: [String: String] = [
        "link": "Custom link patterns are not implemented by the vendored engine; URL and OSC 8 links are supported.",
        "app-notifications": "This engine option applies only to GTK.",
        "async-backend": "Selects the process-wide I/O backend before TOML is loaded; needs startup restructuring.",
        "auto-update": "Needs an application updater.",
        "auto-update-channel": "Needs an application updater.",
        "class": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "config-default-files": "Uses the upstream configuration-file format and search policy; Velocitty loads its own TOML file.",
        "drag-handle": "Needs configurable AppKit window creation, appearance, or state handling.",
        "focus-follows-mouse": "Needs pane layout, focus, and split rendering in the app.",
        "freetype-load-flags": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-custom-css": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-horizontal-tab-scroll": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-opengl-debug": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-quick-terminal-layer": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-quick-terminal-namespace": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-single-instance": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-tabs-location": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-titlebar": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-titlebar-hide-when-maximized": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-titlebar-style": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-toolbar-style": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "gtk-wide-tabs": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "language": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "linux-cgroup": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "linux-cgroup-hard-fail": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "linux-cgroup-memory-limit": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "linux-cgroup-processes-limit": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
        "macos-applescript": "Needs an AppleScript command interface.",
        "macos-custom-icon": "Needs configurable application icon generation/loading; the app has fixed artwork.",
        "macos-dock-drop-behavior": "Needs the corresponding AppKit window, Dock, or launch behavior.",
        "macos-icon": "Needs configurable application icon generation/loading; the app has fixed artwork.",
        "macos-icon-frame": "Needs configurable application icon generation/loading; the app has fixed artwork.",
        "macos-icon-ghost-color": "Needs configurable application icon generation/loading; the app has fixed artwork.",
        "macos-icon-screen-color": "Needs configurable application icon generation/loading; the app has fixed artwork.",
        "macos-non-native-fullscreen": "Needs the corresponding AppKit window, Dock, or launch behavior.",
        "macos-shortcuts": "Needs Shortcuts integration and authorization handling.",
        "macos-titlebar-proxy-icon": "Needs the corresponding AppKit window, Dock, or launch behavior.",
        "middle-click-action": "Needs middle-click event handling and primary-selection clipboard support.",
        "quick-terminal-animation-duration": "Needs a quick-terminal window and activation/focus handling.",
        "quick-terminal-autohide": "Needs a quick-terminal window and activation/focus handling.",
        "quick-terminal-keyboard-interactivity": "Needs a quick-terminal window and activation/focus handling.",
        "quick-terminal-position": "Needs a quick-terminal window and activation/focus handling.",
        "quick-terminal-screen": "Needs a quick-terminal window and activation/focus handling.",
        "quick-terminal-size": "Needs a quick-terminal window and activation/focus handling.",
        "quick-terminal-space-behavior": "Needs a quick-terminal window and activation/focus handling.",
        "resize-overlay": "Needs a resize overlay view.",
        "resize-overlay-duration": "Needs a resize overlay view.",
        "resize-overlay-position": "Needs a resize overlay view.",
        "split-divider-color": "Needs pane layout, focus, and split rendering in the app.",
        "split-inherit-working-directory": "Needs window/tab/pane creation and inheritance policies.",
        "split-preserve-zoom": "Needs pane layout, focus, and split rendering in the app.",
        "tab-inherit-working-directory": "Needs window/tab/pane creation and inheritance policies.",
        "undo-timeout": "Needs an undo/restore model for closed terminals.",
        "unfocused-split-fill": "Needs pane layout, focus, and split rendering in the app.",
        "unfocused-split-opacity": "Needs pane layout, focus, and split rendering in the app.",
        "window-inherit-font-size": "Needs window/tab/pane creation and inheritance policies.",
        "window-inherit-working-directory": "Needs window/tab/pane creation and inheritance policies.",
        "window-new-tab-position": "Needs window/tab/pane creation and inheritance policies.",
        "window-show-tab-bar": "Needs window/tab/pane creation and inheritance policies.",
        "window-subtitle": "Needs configurable AppKit window creation, appearance, or state handling.",
        "window-title-font-family": "Needs configurable AppKit window creation, appearance, or state handling.",
        "window-titlebar-background": "Needs configurable AppKit window creation, appearance, or state handling.",
        "window-titlebar-foreground": "Needs configurable AppKit window creation, appearance, or state handling.",
        "x11-instance-name": "Requires a different platform frontend or font backend; this app uses AppKit and CoreText.",
    ]
}
